name: datainflutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  freezed: ^2.4.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/records.json